version: '3.7'

services:
  currency-exchange:
    image: yashkambaria/yash-mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - '8000:8000'
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      JAVA_OPTS: "-Xms256m -Xmx512m"
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  naming-server:
    image: yashkambaria/yash-mmv2-naming-server:0.0.1-SNAPSHOT
    ports:
      - '8761:8761'
    networks:
      - currency-network
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"


  currency-conversion:
    image: yashkambaria/yash-mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - '8100:8100'
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      JAVA_OPTS: "-Xms256m -Xmx512m"
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  api-gateway:
    image: yashkambaria/yash-mmv2-api-gateway:0.0.1-SNAPSHOT
    ports:
      - '8765:8765'
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      JAVA_OPTS: "-Xms256m -Xmx512m"
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
      - '9411:9411'
    networks:
      - currency-network
    environment:
      JAVA_OPTS: "-Xms256m -Xmx312m"

networks:
  currency-network: